theme: minima
title: Hello, World!
author: Christian Robles
description: I am a back-end developer that has been programming since 8th grade (2013)
defaults:  # can be overriden in the files' front matter
  -
    scope: 
      path: ""
      type: "" # pages, posts, drafts, or any collection
    values:
      layout: "default"
  -
    scope:
      path: "blog/*"
      type: "posts"
    values:
      layout: "post"
      author: "Chris Robles"